sudo: required

language: java

services:
    - docker

before_install:
    - docker build -t alexcoppe/fastqc fastqc/
    - docker build -t alexcoppe/picard picard/
    - docker build -t alexcoppe/mutect mutect/
    - docker build -t alexcoppe/gatk gatk/
    - docker build -t alexcoppe/samtools samtools/
    - docker build -t alexcoppe/varscan varscan/
    - docker build -t alexcoppe/fastx fastx-toolkit/

script:
    - docker run -it --rm alexcoppe/fastqc
    - docker run -it --rm -v $(pwd):/data alexcoppe/picard SortVcf I=/data/test-data/sample.vcf O=/data/sorted.vcf 
    - docker run -it --rm alexcoppe/mutect -h
    - docker run -it --rm alexcoppe/gatk -h
    - docker run -it --rm -v $(pwd):/data alexcoppe/samtools view /data/test-data/sample.bam seq2:450-550
    - docker run -it --rm alexcoppe/varscan
    - docker run -it --rm -v $(pwd):/data alexcoppe/fastx fastx_quality_stats -i /data/test-data/sample.fastq -o /data/stats.txt
